[package]
name = "iSmallTalk"
version = "1.0.0"
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
gtk = "0.16.2"
rand = "0.8.5"
